lsst-ts/ts_xml

sal_interfaces/scheduler/scheduler_Telemetry.xml

1 of 4 pull requests for the parameter addition feature.
@mareuter

adding new parameter to XML

---

sal_interfaces/scheduler/scheduler_Commands.xml
sal_interfaces/scheduler/scheduler_Events.xml
sal_interfaces/scheduler/scheduler_Telemetry.xml

When accepted will squash and merge.

adding topics

---

sal_interfaces/ATThermoelectricCooler/ATThermoelectricCooler_Commands.xml

extra tag was killing xml tests, removed it.

removing extra tag

---

sal_interfaces/MTM2/MTM2_Commands.xml
sal_interfaces/MTM2/MTM2_Events.xml
sal_interfaces/MTM2/MTM2_Telemetry.xml

merging now before being overwritten again

readding MTM2 changes after beinh overwritten by another commit

---

sal_interfaces/SALGenerics.xml
sal_interfaces/Script/Script_Commands.xml
sal_interfaces/Script/Script_Events.xml
sal_interfaces/ScriptQueue/ScriptQueue_Commands.xml
sal_interfaces/ScriptQueue/ScriptQueue_Events.xml
sal_interfaces/Test/Test_Commands.xml
sal_interfaces/Test/Test_Events.xml
sal_interfaces/Test/Test_Telemetry.xml

Revert "TSS-3375: Include logging in BaseCsc"

---

sal_interfaces/SALGenerics.xml

Add command setSimulationMode and event simulationMode.

TSS-3361: Add generic topics for simulation mode

---

sal_interfaces/Script/Script_Commands.xml
sal_interfaces/Script/Script_Events.xml
sal_interfaces/ScriptQueue/ScriptQueue_Events.xml
sal_interfaces/Test/Test_Commands.xml
sal_interfaces/Test/Test_Events.xml

TSS-3326: Shorten the salIndices and pastSalIndices fields

---

sal_interfaces/CatchupArchiver/CatchupArchiver_Events.xml
sal_interfaces/PromptProcessing/PromptProcessing_Events.xml

Updated events in CatchupArchiver and PromptProcessing so that they look the same as AT and MT Archivers.

Updated settingsApplied for CU and PP.

---

sal_interfaces/TunableLaser/TunableLaser_Events.xml

Adding in TunableLaser detailed States.

Add TunableLaser detailedStates

---

sal_interfaces/TunableLaser/TunableLaser_Events.xml
sal_interfaces/TunableLaser/TunableLaser_Telemetry.xml

- added wavelengthChanged event.

Added all temperature sensors to telemetry

---

sal_interfaces/ATPneumatics/ATPneumatics_Events.xml

Testing Jenkins integration.

---

sal_interfaces/ATSpectrograph/ATSpectrograph_Events.xml

Simplify the interface by using consistent names and remove unused enumerations.

Update xml definition for atSpectrograph. 

---

sal_interfaces/ATAOS/ATAOS_Events.xml

Modify focusCorrectionStarted and focusCorrectionCompleted events to add azimuth and elevation.

DM-18520: ATPointing + ATAOS integration test

---

sal_interfaces/ATWhiteLight/ATWhiteLight_Commands.xml
sal_interfaces/ATWhiteLight/ATWhiteLight_Events.xml
sal_interfaces/ATWhiteLight/ATWhiteLight_Telemetry.xml

merged chiller commands into ATWhiteLight, and renamed some vague ones like "powerOn" so that it's clear we're talking about the chiller and not the entire white light subsystem.

Chillermerge

---

sal_interfaces/MTAOS/MTAOS_Commands.xml

Add the intra- and extra-focal visits in MTAOS_command_processIntraExtraWavefrontError.

Add the intra- and extra-focal visits in MTAOS

---

sal_interfaces/MTAOS/MTAOS_Commands.xml
sal_interfaces/MTAOS/MTAOS_Events.xml
sal_interfaces/MTAOS/MTAOS_Telemetry.xml

Add the description and unit to MTAOS xml and support IOTA.

Add the description and unit to MTAOS xml and support IOTA.

---

sal_interfaces/MTM2/MTM2_Commands.xml
sal_interfaces/MTM2/MTM2_Events.xml
sal_interfaces/MTM2/MTM2_Telemetry.xml

Add the description and unit to MTM2 xml.

Add the description and unit to MTM2 xml.

---

sal_interfaces/ATAOS/ATAOS_Commands.xml
sal_interfaces/ATAOS/ATAOS_Events.xml
sal_interfaces/ATAOS/ATAOS_Telemetry.xml
sal_interfaces/ATMonochromator/ATMonochromator_Commands.xml
sal_interfaces/ATSpectrograph/ATSpectrograph_Commands.xml
sal_interfaces/ATSpectrograph/ATSpectrograph_Events.xml
sal_interfaces/ATSpectrograph/ATSpectrograph_Telemetry.xml
sal_interfaces/ATTCS/ATTCS_Commands.xml
sal_interfaces/ATTCS/ATTCS_Events.xml
sal_interfaces/ATTCS/ATTCS_Telemetry.xml
sal_interfaces/DIMM/DIMM_Events.xml
sal_interfaces/DIMM/DIMM_Telemetry.xml
sal_interfaces/Electrometer/Electrometer_Commands.xml
sal_interfaces/Electrometer/Electrometer_Events.xml
sal_interfaces/Environment/Environment_Events.xml
sal_interfaces/Environment/Environment_Telemetry.xml

- ATAOS
- ATMonochromator
- ATSpectrograph
- ATTCS
- DIMM
- Electrometer

First pass of units and descriptions for

---

sal_interfaces/ATPtg/ATPtg_Commands.xml
sal_interfaces/ATPtg/ATPtg_Events.xml
sal_interfaces/ATPtg/ATPtg_Telemetry.xml
sal_interfaces/MTPtg/MTPtg_Commands.xml
sal_interfaces/MTPtg/MTPtg_Events.xml
sal_interfaces/MTPtg/MTPtg_Telemetry.xml

Adding startTracking command to ATPtg commands.
Adding elLimitWarning event to ATPtg and MTPtg events.
Added azWrapStrategy and timeOnTarget in raDecTarget command.
Fixed some units and descriptions.

Ticket TPC-171

---

sal_interfaces/ATSpectrograph/ATSpectrograph_Events.xml

Add instrument port information to `settingsApplied` event in the ATSpectrograph.

DM-19849: Make ATSpectrograph configurable

---

sal_interfaces/ATPtg/ATPtg_Telemetry.xml
sal_interfaces/MTPtg/MTPtg_Commands.xml
sal_interfaces/MTPtg/MTPtg_Telemetry.xml

New item skyEnvironment telemetry added to ATPtg and MTPtg.
startTracking command added to MTPtg.
MTPtg's debugLevel command's item fixed.

Adding skyEnvironment telemetry to ATPtg and MTPtg

---

sal_interfaces/Hexapod/Hexapod_Commands.xml
sal_interfaces/Rotator/Rotator_Commands.xml

Add the stop command for hexapod and rotator.

Add the stop command for hexapod and rotator.

---

sal_interfaces/FiberSpectrograph/FiberSpectrograph_Commands.xml
sal_interfaces/FiberSpectrograph/FiberSpectrograph_Events.xml
sal_interfaces/FiberSpectrograph/FiberSpectrograph_Telemetry.xml
sal_interfaces/SALSubsystems.xml

Update FiberSpectrograph XML to reflect changes needed for initial CSC implementation.

DM-20740: Implement FiberSpectrograph CSC version 1

---

sal_interfaces/SALGenerics.xml

https://jira.lsstcorp.org/browse/DM-21734

Add settingsApplied and softwareVersions to the SALGenerics.xml

---

sal_interfaces/MTHeaderService/MTHeaderService_Events.xml

Removing settingsApplied for MTHeaderService

---

sal_interfaces/ATPtg/ATPtg_Events.xml
sal_interfaces/ATPtg/ATPtg_Telemetry.xml
sal_interfaces/MTPtg/MTPtg_Events.xml
sal_interfaces/MTPtg/MTPtg_Telemetry.xml

Removing settingsApplied events from ATPtg and MTPtg. (TPC-173)

Removing settingsApplied events from ATPtg and MTPtg.

---

sal_interfaces/ATCamera/ATCamera_Telemetry.xml

Fix for CAP-381 (fan_I -> otm_I)

Fix incorrectly named channel

---

sal_interfaces/MTVMS/MTVMS_Events.xml

I followed the same idea as in #181 to get DM-22509 done, that fixes CAP-367. If the solution is not perfect please, feel free to comment as much as needed.

DM-22509: MTVMS: Rename settingsApplied event

---

sal_interfaces/MTVMS/MTVMS_Telemetry.xml

See: https://jira.lsstcorp.org/browse/DM-22155

DM-22155: MTVMS fix to conform topic naming convention

---

sal_interfaces/MTM1M3/MTM1M3_Telemetry.xml
tests/test_NoReservedWords.py

See: https://jira.lsstcorp.org/browse/DM-22621

DM-22621: MTM1M3 - use of InfluxDB Reserved Words

---

sal_interfaces/Hexapod/Hexapod_Events.xml
sal_interfaces/Rotator/Rotator_Events.xml
tests/test_AttributeDescription.py
tests/test_AttributeNaming.py
tests/test_TopicNaming.py

And enable the associated unit test

DM-23165: add a description to Hexapod commandableByDds event

---

sal_interfaces/ATCamera/ATCamera_Telemetry.xml

Please include in 4.7 release. Needed for CAP-423.

Add additional AuxTel WREB telemetry item for HVSwitch (CAP-423)

---

python/lsst/ts/xml/testutils.py
sal_interfaces/ESS/ESS_Telemetry.xml
sal_interfaces/SALSubsystems.xml

New CSC for rpi based sensor telemetry

Add ESS - Environmental Sensor System

---

sal_interfaces/CCCamera/CCCamera_Telemetry.xml

Fix CAP-461

---

sal_interfaces/ATCamera/ATCamera_Commands.xml
sal_interfaces/CCCamera/CCCamera_Commands.xml
sal_interfaces/MTCamera/MTCamera_Commands.xml

Add stop command for ATCamera/CCCamera/MTCamera (CAP-486)

Add stop command (as documented in LSE-71)

---

sal_interfaces/Dome/Dome_Events.xml

to match elMotion and the enabled events.

Rename azMotion.motionState to azMotion.state

---

sal_interfaces/Dome/Dome_Events.xml
sal_interfaces/ESS/ESS_Telemetry.xml
tests/test_enumeration.py

Add unit test to check enumeration integrity.

Fix Dome enumeration.

---

sal_interfaces/SALSubsystems.xml

For SALSubsystems I have some connection with.
Also update a few fields for more subystems, updating a deprecated value
with the desired replacement.

DM-25739: Update SALSubsystems.xml

---

sal_interfaces/MTM2/MTM2_Commands.xml
sal_interfaces/MTM2/MTM2_Telemetry.xml

Implement some additional changes to M2 xml.

DM-25475: Implement M2 LUT behavior in m2 simulator

---

sal_interfaces/CCCamera/CCCamera_Events.xml

This is a "preview" of a fix for CAP-492. It will probably not be used with XML 6.1, but might be useful to start further discussion and for experimentation. The idea would be to iterate on these events for XML 6.2. These are entirely new events, so hopefully the scope for introducing problems is small.

Preview proposed solution for CAP-492

---

sal_interfaces/SALSubsystems.xml

* Fixed TunableLaser, Electrometer, ATHexapod, CBP and LinearStage

Comply with new SALSubsystems attributes requirements

---

.gitignore
sal_interfaces/SALSubsystems.xml

Also added tests/results directory to .gitignore because it was generated by pytest.

Update CBP documentation and simulator information

---

sal_interfaces/Hexapod/Hexapod_Events.xml
sal_interfaces/Rotator/Rotator_Events.xml
sal_interfaces/Rotator/Rotator_Telemetry.xml

also fix a mispelling in an ApplicationStatus enum for Hexapod and Rotator

DM-26107: add a few fields to Rotator topics

---

sal_interfaces/SALSubsystems.xml
tests/test_Generics.py
tests/test_SALSubsystems.py
tests/test_black.py

fills in some required fields for SummitFacility CSC in SalSubsystems.xml

updated SummitFacility

---

sal_interfaces/SALSubsystems.xml

Both ATArchiver and CCArchiver change from ConfigurableCSC to BaseCSC

Change ATArchiver and CCArchiver to Not Configurable

---

sal_interfaces/CBP/CBP_Events.xml
sal_interfaces/CBP/CBP_Telemetry.xml

* Updated status fields to booleans instead of integers

Added target and motion events to CBP

---

sal_interfaces/ATPtg/ATPtg_Commands.xml
sal_interfaces/ATPtg/ATPtg_Events.xml
sal_interfaces/MTPtg/MTPtg_Commands.xml
sal_interfaces/MTPtg/MTPtg_Events.xml

Adding new event validatedTarget and new item validateOnly to target commands. (TPC-182)

Adding new event validatedTarget and new item validateOnly to target commands. (TPC-182)

---

sal_interfaces/MTM1M3/MTM1M3_Commands.xml
sal_interfaces/MTM1M3/MTM1M3_Events.xml

Added bump test and kill bump test commands and bump test status event.

DM-27228: FA bump test

---

sal_interfaces/LOVE/LOVE_Commands.xml

replacing the three commands that supported the same behavior

DM-28847: Copy Authorize_command_requestAccess to LOVE

---

sal_interfaces/ATPtg/ATPtg_Events.xml
sal_interfaces/MTPtg/MTPtg_Events.xml

Adding pointData event to ATPtg and MTPtg.

---

sal_interfaces/ATCamera/ATCamera_Commands.xml
sal_interfaces/CCCamera/CCCamera_Commands.xml
sal_interfaces/MTCamera/MTCamera_Commands.xml

Getting my fixes for xml 9.1 in early for a change!

Fix for CAP-752

---

sal_interfaces/MTM1M3/MTM1M3_Commands.xml
sal_interfaces/MTM1M3/MTM1M3_Telemetry.xml

Vastly improved description of M1M3 commands. Added units to command
parameters. Dropped unused commands.

Address comments in LTS-161

---

sal_interfaces/MTM1M3/MTM1M3_Events.xml

Adds various M1M3 settings. Skipped complex things (matrices and SafetyControllerSettings), as this will be part of the next PR.

Add various M1M3 settings

---

sal_interfaces/SALSubsystems.xml

Fix Configuration entry for MTHexapod and MTRotator
Change ProductOwner from Bo Xin to Sandrine Thomas

CAP-802: SALSubsystems.xml updates

---

README.md
doc/salsubsystems_attributes.rst
python/lsst/ts/xml/generate_subsystems_doc.py
python/lsst/ts/xml/testutils.py
sal_interfaces/SALGenerics.xml
sal_interfaces/SALSubsystems.xml
tests/test_SALSubsystems.py

Add subsystem field to generic command_setLogLevel and logevent_logLevel topics.
Add timestamp field to generic logevent_logMessage topic.

DM-32429: Add fields to generic log topics

---

schema/SALCommandSet.xsd
schema/SALEventSet.xsd
schema/SALTelemetrySet.xsd

Added IsJavaSchema  to each itemType

Add IsJavaArray to schemas

---

sal_interfaces/MTHexapod/MTHexapod_Events.xml
sal_interfaces/MTRotator/MTRotator_Events.xml

change MTHexapod application status to a scalar from an array

DM-32836: change interlock.detail to interlock.enabled for MTHexapod and MTRotator

---

sal_interfaces/MTHexapod/MTHexapod_Events.xml
sal_interfaces/MTRotator/MTRotator_Events.xml

to a have a single "connected" field

CAP-856: MTHexapod and MTRotator: change connected event

---

sal_interfaces/SALSubsystems.xml

Remove SALPY from RuntimeLanguages

---

python/lsst/ts/xml/testutils.py
sal_interfaces/MTAirCompressor/MTAirCompressor_Commands.xml
sal_interfaces/MTAirCompressor/MTAirCompressor_Events.xml
sal_interfaces/MTAirCompressor/MTAirCompressor_Telemetry.xml
sal_interfaces/SALSubsystems.xml

- AirCompressors schema
- Timer event
- Status data

MTAirCompressor CsC

---

sal_interfaces/MTM1M3TS/MTM1M3TS_Commands.xml
sal_interfaces/MTM1M3TS/MTM1M3TS_Events.xml

- added engineerMode flag
- enableEngineeringMode command

Thermal system engineering mode

---

sal_interfaces/CCCamera/CCCamera_Events.xml
sal_interfaces/MTCamera/MTCamera_Events.xml

Fix instances where strings had count>1 (CAP-894)

Fix for CAP-894

---

sal_interfaces/Scheduler/Scheduler_Commands.xml
sal_interfaces/Scheduler/Scheduler_Events.xml

* Add new `computePredictedSchedule` command.
* Add new events:
* `generalInfo`, to publish some general information about the scheduler.
* `timeToNextTarget`, to publish information about upcomming targets.
* `predictedSchedule`, to publish the predicted schedule.

In Scheduler:

---

sal_interfaces/ESS/ESS_Telemetry.xml
sal_interfaces/MTVMS/MTVMS_Telemetry.xml

Added PSD telemetry and ESS accelerometers.

---

sal_interfaces/MTMount/MTMount_Commands.xml
sal_interfaces/MTMount/MTMount_Events.xml

DM-35126: MTMount: add homeBothAxes command plus other tweaks

---

sal_interfaces/ATWhiteLight/ATWhiteLight_Events.xml

and standardize format of some other alarm and warning codes

DM-35753: Fix ATWhiteLight ChillerL21Alarm codes

---

sal_interfaces/MTM1M3/MTM1M3_Commands.xml
sal_interfaces/MTM1M3/MTM1M3_Events.xml
sal_interfaces/MTM1M3/MTM1M3_Telemetry.xml
sal_interfaces/MTM1M3TS/MTM1M3TS_Commands.xml
sal_interfaces/MTM1M3TS/MTM1M3TS_Events.xml
sal_interfaces/MTM1M3TS/MTM1M3TS_Telemetry.xml

- M1M3 Thermal System auxiliary devices
- remove aberration forces
- moved events into telemetry

DM-35056: turn some events into telemetry

---

sal_interfaces/MTM1M3TS/MTM1M3TS_Commands.xml
sal_interfaces/MTM1M3TS/MTM1M3TS_Events.xml
sal_interfaces/MTM1M3TS/MTM1M3TS_Telemetry.xml

* VFD Pump controller
* Flow meter

M1M3 Thermal System auxiliary devices

---

sal_interfaces/MTCamera/MTCamera_Events.xml
sal_interfaces/MTCamera/MTCamera_Telemetry.xml

See if this makes the main camera filter changer XML compilable by SAL

Update FCS telemetry and events to level 1

---

python/lsst/ts/xml/data/sal_interfaces/MTVMS/MTVMS_Commands.xml
python/lsst/ts/xml/data/sal_interfaces/MTVMS/MTVMS_Events.xml
python/lsst/ts/xml/data/sal_interfaces/MTVMS/MTVMS_Telemetry.xml

- Changed Hz to ms/frequency to period
- Added miscellaneous fields

VMS miscellaneous fields

---

python/lsst/ts/xml/data/sal_interfaces/MTM1M3/MTM1M3_Commands.xml
python/lsst/ts/xml/data/sal_interfaces/MTM1M3/MTM1M3_Events.xml
python/lsst/ts/xml/data/sal_interfaces/MTM1M3/MTM1M3_Telemetry.xml

- Fixed Description strings
- total force/moment

Fix M1M3 description strings

---

python/lsst/ts/xml/data/sal_interfaces/Script/Script_Events.xml
python/lsst/ts/xml/data/sal_interfaces/ScriptQueue/ScriptQueue_Events.xml

Add instrument field to the Script metadata event
and to the ScriptQueue nextVisit event.

DM-38545: Script and ScriptQueue: add instrument field

---

python/lsst/ts/xml/data/sal_interfaces/ATWhiteLight/ATWhiteLight_Events.xml

Replace StandbyOrOn with Standby and On.
Eliminate Off -- use Unknown instead.

DM-38560: ATWhiteLight: update LampControllerState enums

---

doc/version-history.rst
python/lsst/ts/xml/data/sal_interfaces/ESS/ESS_Telemetry.xml

DM-39688: Fix units of accelerationPSDX/Y/Z

---

doc/version-history.rst
pyproject.toml
python/lsst/ts/xml/data/sal_interfaces/MTM2/MTM2_Commands.xml
python/lsst/ts/xml/data/sal_interfaces/MTM2/MTM2_Events.xml
python/lsst/ts/xml/data/sal_interfaces/MTM2/MTM2_Telemetry.xml

* Remove the unrecognized pytest flags in **pyproject.toml**.
* MTM2:
* Update the MTM2 interface to have the similar functionality as EUI.

Update the M2 xml.

---

doc/version-history.rst
python/lsst/ts/xml/data/sal_interfaces/MTHexapod/MTHexapod_Telemetry.xml

* MTHexapod
* Fix and improve the description in ``MTHexapod_actuators`` topic.
* Add the new item ``copleyFaultStatus`` and improve the description in ``MTHexapod_electrical`` topic.

Update the telemetry of MTHexapod.

---

doc/version-history.rst
python/lsst/ts/xml/data/sal_interfaces/MTM2/MTM2_Commands.xml
python/lsst/ts/xml/data/sal_interfaces/MTM2/MTM2_Events.xml
python/lsst/ts/xml/enums/MTM2.py

Add the M2 command to kill the bump test.

Add the M2 command to kill the bump test.

---

doc/version-history.rst
python/lsst/ts/xml/data/sal_interfaces/MTM2/MTM2_Commands.xml

Add the MTM2_command_setHardpointList.

Add the MTM2_command_setHardpointList.

---

doc/version-history.rst
python/lsst/ts/xml/tables/m1m3/fa_table.py
tests/test_Units.py
tests/test_tables_m1m3.py

- Add quadrant property to M1M3 FATable
- fixed black formatting

Add quadrant property to M1M3 ForceActuator

---

doc/version-history.rst
python/lsst/ts/xml/data/sal_interfaces/MTM2/MTM2_Telemetry.xml

Improve the document of MTM2.

---

doc/version-history.rst
python/lsst/ts/xml/data/sal_interfaces/MTRotator/MTRotator_Commands.xml

* Add the new commands: ``MTRotator_command_configureEmergencyAcceleration`` and ``MTRotator_command_configureEmergencyJerk``.

Add the new rotator commands.

---

doc/version-history.rst

Fixed the version number in doc/version-history.rst

---

doc/news/CAP-1029.feature.rst
python/lsst/ts/xml/data/sal_interfaces/ATCamera/ATCamera_Events.xml
python/lsst/ts/xml/data/sal_interfaces/CCCamera/CCCamera_Events.xml
python/lsst/ts/xml/data/sal_interfaces/MTCamera/MTCamera_Events.xml
python/lsst/ts/xml/data/sal_interfaces/MTCamera/MTCamera_Telemetry.xml

Fix many missing units/descriptions
Add mpm subsystem for MTCamera
Update MTCamera telemetry/events for filter changer subsystem
Update MTCamera telemetry/events for shutter subsystem
Update MTCamera telemetry/events for refrig/chiller subsystems

Cap 1029 -- catch all update for camera xml 20.3

---

doc/news/interface_changes/CAP-1024.mtcamera.rst
doc/news/interface_changes/CAP-1025.mtcamera.rst
python/lsst/ts/xml/data/sal_interfaces/MTCamera/MTCamera_Commands.xml
python/lsst/ts/xml/data/sal_interfaces/MTCamera/MTCamera_Events.xml

Add support for filter changer low power mode (CAP-1024)
Add support for filter changer degraded mode (CAP-1025)
See https://docs.google.com/document/d/1JFpjZts4OPaXDaHRJeDRlxIZdRNNPJ5enHpLhJDlXQM/edit?usp=sharing

Implement CAP-1024 and CAP-1025

---

doc/news/interface_changes/CAP-1030.mtcamera.rst
python/lsst/ts/xml/data/sal_interfaces/MTCamera/MTCamera_Events.xml
python/lsst/ts/xml/data/sal_interfaces/MTCamera/MTCamera_Telemetry.xml

Fix issues related to MTCamera thermal patterns for rtd and trim heaters

Implement CAP-1030 -- changes to MTCamera hex/thermal systems

---

doc/news/interface_changes/DM-43428.atbuilding.rst
python/lsst/ts/xml/data/sal_interfaces/ATBuilding/ATBuilding_Commands.xml
python/lsst/ts/xml/data/sal_interfaces/ATBuilding/ATBuilding_Events.xml
python/lsst/ts/xml/data/sal_interfaces/ATBuilding/ATBuilding_Telemetry.xml
python/lsst/ts/xml/enums/ATBuilding.py

I am `ts_xml` n00b, but this is a first attempt based on looking over existing xml for other CSCs.
These interfaces are ahead of the corresponding CSC codes, but would like to get the XML in so we can test these when ready and possibly make available before the next cycle.

Additions for auxtel vent gates/fan

---

python/lsst/ts/xml/data/sal_interfaces/MTCamera/MTCamera_Events.xml

Emergency fix for Cycle 36 (copy of fix for Cycle 35). CAP-1031

Emergency fix for Cycle 36 (copy of fix for Cycle 35). CAP-1031

---

doc/news/interface_changes/DM-42566.mtm2.rst
python/lsst/ts/xml/data/sal_interfaces/MTM2/MTM2_Events.xml

Add the MTM2_logevent_bypassedIlc.

Add the MTM2_logevent_bypassedIlc.

---

doc/news/DM-43819.mtm1m3
python/lsst/ts/xml/data/sal_interfaces/MTM1M3/MTM1M3_Commands.xml
python/lsst/ts/xml/data/sal_interfaces/MTM1M3/MTM1M3_Events.xml
python/lsst/ts/xml/data/sal_interfaces/MTM1M3/MTM1M3_Telemetry.xml
tests/test_TopicDescription.py

Added missing Description entries

---

doc/news/DM-43815.mtaircompressor
python/lsst/ts/xml/data/sal_interfaces/MTAirCompressor/MTAirCompressor_Events.xml
tests/test_TopicDescription.py

Add missing Description entries

---

doc/news/interface_changes/DM-44083.tunablelaser.rst
python/lsst/ts/xml/data/sal_interfaces/TunableLaser/TunableLaser_Events.xml
python/lsst/ts/xml/enums/TunableLaser.py

Associated with https://github.com/lsst-ts/ts_TunableLaser/pull/52

updating tunable laser states

---

doc/news/interface_changes/DM-43820.mtm1m3ts
python/lsst/ts/xml/data/sal_interfaces/MTM1M3TS/MTM1M3TS_Commands.xml
python/lsst/ts/xml/data/sal_interfaces/MTM1M3TS/MTM1M3TS_Events.xml
python/lsst/ts/xml/data/sal_interfaces/MTM1M3TS/MTM1M3TS_Telemetry.xml
tests/test_TopicDescription.py

Add M1M3 Thermal XML Description entries.

---

doc/news/CAP-1047.atcamera.rst
doc/news/CAP-1047.cccamera.rst
doc/news/CAP-1047.mtcamera.rst
python/lsst/ts/xml/data/sal_interfaces/ATCamera/ATCamera_Events.xml
python/lsst/ts/xml/data/sal_interfaces/CCCamera/CCCamera_Events.xml
python/lsst/ts/xml/data/sal_interfaces/MTCamera/MTCamera_Events.xml
python/lsst/ts/xml/data/sal_interfaces/MTCamera/MTCamera_Telemetry.xml

Updated XML corresponding to deployed versions of CCS subsystems for AT/CC/MTCamera

Update for AT/CC/MTCamera for XML 22

---

doc/news/DM-45475.misc.rst
doc/news/interface_changes/DM-45475.atmonochromator.rst
python/lsst/ts/xml/enums/ATMonochromator.py

This should be merged as part of xml-23. Also, when merged, will need to change some of the scripts so that they align with the updated configuration.

updated grating enumeration

---

doc/news/interface_changes/CAP-1056.atcamera.rst
doc/news/interface_changes/CAP-1056.cccamera.rst
doc/news/interface_changes/CAP-1056.mtcamera.rst
python/lsst/ts/xml/data/sal_interfaces/CCCamera/CCCamera_Events.xml
python/lsst/ts/xml/data/sal_interfaces/MTCamera/MTCamera_Events.xml
python/lsst/ts/xml/data/sal_interfaces/MTCamera/MTCamera_Telemetry.xml

Miscellaneous update for CCCamera/MTCamera dictionary changes

Fixes for CAP-1056

---

doc/news/interface_changes/DM-46022.mtm1m3.rst
python/lsst/ts/xml/data/sal_interfaces/MTM1M3/MTM1M3_Events.xml

DM-44022: fix misleading MTM1M3 DetailedState comment

---

doc/news/interface_changes/DM-47994.mtrotator.rst
python/lsst/ts/xml/enums/MTRotator.py

Update the ErrorCode enum in MTRotator.py.

Update the error code of rotator.

---

doc/news/interface_changes/DM-48784.dimm.rst
python/lsst/ts/xml/data/sal_interfaces/DIMM/DIMM_Commands.xml
python/lsst/ts/xml/data/sal_interfaces/DIMM/DIMM_Events.xml
python/lsst/ts/xml/data/sal_interfaces/DIMM/DIMM_Telemetry.xml
python/lsst/ts/xml/enums/DIMM.py

The DIMM CSC has some shortcomings and some discrepancies between the XML and the actual implementation of the DIMM.

DM-48784 Revisions for DIMM CSC

---

doc/news/interface_changes/CAP-1064.mtcamera.rst
python/lsst/ts/xml/data/sal_interfaces/MTCamera/MTCamera_Events.xml

Updates to MTEvents.xml for filter changer, previously missed from CAP-1064

Commit MTCamera_Events.xml with events previously missed from CAP-1064

---

doc/news/interface_changes/CAP-1066.mtcamera.rst
python/lsst/ts/xml/data/sal_interfaces/MTCamera/MTCamera_Events.xml

Add MTCamera_logevent_rebCond

---

doc/news/interface_changes/DM-49413.ess.rst
python/lsst/ts/xml/data/sal_interfaces/ESS/ESS_Events.xml

This event makes it possible to load SOAR RINGSS data into the EFD.

DM-49413 Add ringssMeasurement event to ESS

---

doc/news/interface_changes/DM-48237-II.mtm1m3.rst
python/lsst/ts/xml/tables/m1m3/fa_table.py

ForceActuatorData.distance method

---

doc/news/interface_changes/DM-49538-II.mtm1m3ts.rst
python/lsst/ts/xml/data/sal_interfaces/MTM1M3TS/MTM1M3TS_Commands.xml
python/lsst/ts/xml/data/sal_interfaces/MTM1M3TS/MTM1M3TS_Events.xml

Glycol and heaters setpoint in applied temperature. FCU target values reported in an event, removed MPU status.

---

doc/news/interface_changes/DM-50296.mthexapod.rst
python/lsst/ts/xml/data/sal_interfaces/MTHexapod/MTHexapod_Commands.xml

Add the ``MTHexapod_command_moveInSteps`` and ``MTHexapod_command_offsetInSteps`` topics.

Add the hexapod moveInSteps and offsetInSteps commands.

---

doc/news/interface_changes/DM-33284.mtm1m3.rst
python/lsst/ts/xml/data/sal_interfaces/MTM1M3/MTM1M3_Events.xml
python/lsst/ts/xml/enums/MTM1M3.py

WAITINGTENSION, WAITINGCOMPRESSION HP states
