lsst-ts/ts_xml

- sal_interfaces/Test/Test_Events.xml
diff --git a/sal_interfaces/Test/Test_Events.xml b/sal_interfaces/Test/Test_Events.xml
index 95b1503..749fd51 100644
--- a/sal_interfaces/Test/Test_Events.xml
+++ b/sal_interfaces/Test/Test_Events.xml
@@ -35,6 +35,21 @@
<Count>1</Count>
</item>
</SALEvent>
+<SALEvent>
+    <Subsystem>Test</Subsystem>
+    <Version>1.0.0</Version>
+    <Author></Author>
+    <EFDB_Topic>Test_logevent_heartbeat</EFDB_Topic>
+    <Alias>heartbeat</Alias>
+    <Explanation>http://sal.lsst.org</Explanation>
+    <item>
+        <EFDB_Name>heartbeat</EFDB_Name>
+        <Description></Description>
+        <IDL_Type>boolean</IDL_Type>
+        <Units></Units>
+        <Count>1</Count>
+    </item>
+</SALEvent>
<SALEvent>
<Subsystem>Test</Subsystem>
<Version>1.0.0</Version>
> TSS-3132: Add the "heartbeat" event to the Test component in ts_xml

- sal_interfaces/ATDome/ATDome_Commands.xml
- sal_interfaces/ATDome/ATDome_Events.xml
and move descriptive text to comments
> DM-17769: Restore Explanation fields to the original urls in ATDome XML

- sal_interfaces/ATPtg/ATPtg_Telemetry.xml
- sal_interfaces/MTPtg/MTPtg_Telemetry.xml
Renamed attribute 'localTime' to 'localTimeString' to avoid using MySQL reserved word LOCALTIME.
> Renamed attribute 'localTime' to 'localTimeString'.

- sal_interfaces/ATWhiteLight/ATWhiteLight_Commands.xml
- sal_interfaces/ATWhiteLight/ATWhiteLight_Events.xml
- sal_interfaces/ATWhiteLight/ATWhiteLight_Telemetry.xml
- sal_interfaces/MTAOS/MTAOS_Commands.xml
this updates ts_xml with changes for the AT White Light Source CSC. It adds 
emergencyPowerOff: a command for "emergency" power off, which overrides enforcement of mandatory cooldown and warmup periods designed to extend the life of the bulb. 
wattageChange: the event that is published whenever the KiloArc reports a change in status now includes changes to the wattage output of the bulb
bulbHours and bulbWattHours: telemetry topics that report the uptime of the bulb, so we know when it's getting to be time to replace it
> At whitelight additions

- sal_interfaces/ATPtg/ATPtg_Commands.xml
- sal_interfaces/MTPtg/MTPtg_Commands.xml
TPC-166. trackId attribute is added to ATPtg and MTPtg's raDecTarget, azElTarget, ephemTarget and planetTarget commands.
> trackId attribute added to target commands of ATPtg and MTPtg

- sal_interfaces/Watcher/Watcher_Commands.xml
- sal_interfaces/Watcher/Watcher_Events.xml
Use Description instead of Explanation for topics.
Add missing description for the heartbeat event.
> DM-20471: Fix minor errors in Watcher XML

- sal_interfaces/ATWhiteLight/ATWhiteLight_Events.xml
Accidentally pushed some changes to atwhitelight events xml straight to develop...Original push was adding unique event topics for each of the chiller's warnings... this PR fixes the non-unique alias fields that were in those changes.
> fixed white light event aliases to be unique

- python/lsst/ts/xml/testutils.py
- tests/test_NoReservedWords.py
The Reserved Word tests now check IDL, DB Critical and DB Optional as three separate tests.  As DB optional words become critical, simply remove the words from the optional list and add them to the critical list in testutils.py
> Split the Reserved Word tests into three parts

- sal_interfaces/ATAOS/ATAOS_Commands.xml
- sal_interfaces/ATAOS/ATAOS_Events.xml
Include commands to apply offset to all axis at the same time cumulatively.
Include commands to reset offsets each axis individually or to all axis at the same time.
Include event with applied offset.
Adds `applyAxisOffset` to ATAOS command set.
> DM-22700: Include command to add offsets to the lookup tables in ATAOS.

- sal_interfaces/MTM1M3/MTM1M3_Commands.xml
Thermal system is controlled by Thermal Subsystem. Its commands are
defined in MTM1M3TS. SS (Support System) cannot control thermal
subsystem.
> removed setThermalSetpoint

- sal_interfaces/SALSubsystems.xml
I missed two important comments made by @rbovill in the first review of DM-25739: change Simulator tag to a URL to the dedicated simulator packages for ATMCS and ATPneumatics.
I also updated the Github entries for Hexapod and Rotator to remove links to vendor code for the low-level controllers, based on Michael R's recommendation.
> DM-25739: Fix a few entries that I missed the first time.

- sal_interfaces/SALSubsystems.xml
Because some simulator software does not exist on their gitlap repos I compiled all the simulators into a zip file in the La Serena PDM server.
> adding file path to MTMount simiulator software

- sal_interfaces/MTM1M3/MTM1M3_Commands.xml
Shutdown functionality shall be provided by generic exitControl command.
> DM-24838: Removed M1M3's shutdown command

- sal_interfaces/ATPtg/ATPtg_Telemetry.xml
- sal_interfaces/MTPtg/MTPtg_Telemetry.xml
Update pointing component interface to replace string for double in topic attributes with values.
> DM-25909: Update telemetry topics in ATPtg and MTPtg to publish values as floats instead of sexagesimal strings

- sal_interfaces/SALSubsystems.xml
* Added CPP and SALPY to the RuntimeLanguages field for the Script CSC.  SALPY is needed for the SAL python unit tests, and C++ is needed to create the SALPY library. 
* Added CPP, SALPY, Java and LabVIEW to the RuntimeLanguages list for the Test CSC. Since Test is for testing SAL, it should probably build all the libraries, and C++ and SALPY are required to run the unit tests, anyway.
> Update RuntimeLanguages field for Script and Test

- sal_interfaces/ATCamera/ATCamera_Events.xml
- sal_interfaces/CCCamera/CCCamera_Events.xml
- sal_interfaces/MTCamera/MTCamera_Events.xml
When using emulated DAQ, add emulatedImage name to the end of image telemetry, to make it possible for @menanteau to add it to header service if desired.
> Add new item to endOfImageTelemetry: emulatedImage

- sal_interfaces/Test/Test_Commands.xml
- sal_interfaces/Test/Test_Events.xml
- sal_interfaces/Test/Test_Telemetry.xml
Note that no other SAL components use either of these two data types.
> DM-31017: Test: remove char and octet fields

- sal_interfaces/ATCamera/ATCamera_Events.xml
- sal_interfaces/CCCamera/CCCamera_Events.xml
- sal_interfaces/MTCamera/MTCamera_Events.xml
Additions to support Calibration mode, see discussion at https://lsstc.slack.com/archives/CLQ63T89L/p1647278833410459 and https://jira.lsstcorp.org/browse/CAP-870
It particular this change adds two new items to startIntegration event, and adds an additional state (DISCARDING) to raftsDetailedState.
@menanteau Note that the intention is that the header service starts using the new timeout item in startIntegration to determine the header service timeout, instead of the current behavior of using expTime.
> Implement CAP-870

- sal_interfaces/MTMount/MTMount_Events.xml
There is no hurry on this. It can wait for ts_xml 12.
I do want the ts_idl update to be in cycle 25 build so INRIA can use it, but I doubt any C++ or Java code will be using the MTMount enum values defined here in ts_xml.
> DM-34357: MTMount: fix LimitsMask enum values.

- python/lsst/ts/xml/testutils.py
- sal_interfaces/ScriptQueue/ScriptQueue_Commands.xml
- sal_interfaces/ScriptQueue/ScriptQueue_Events.xml
- tests/test_NoReservedWords.py
And update the test of reserved words to catch use of "salIndex".
> DM-34771: rename "salIndex" public ScriptQueue fields to "scriptSalIndex"

- sal_interfaces/ATCamera/ATCamera_Events.xml
- sal_interfaces/ATCamera/ATCamera_Telemetry.xml
- sal_interfaces/CCCamera/CCCamera_Events.xml
- sal_interfaces/CCCamera/CCCamera_Telemetry.xml
- sal_interfaces/MTCamera/MTCamera_Events.xml
- sal_interfaces/MTCamera/MTCamera_Telemetry.xml
This pull request cleanup XML prior to add new camera XML for filter changer and shutter. See CAP-932:
There are 3 changes, all hopefully innocuous
Change length of ===== commands to match text
Add a new comment: CCS: Dictionary_Checksum: 4128750188L for each computer generated topic. This has no effect on the generated SAL code, but will allow us to do cross checks when running CCS to find outdated XML
Correct a few units (in partcular some unitless->milliseconds that I missed when I fixed them up by hand before.
These changes are just cleanup before more substantive changes to follow
> Cleanup auto-generated XML prior to camera changes

- sal_interfaces/MTCamera/MTCamera_Telemetry.xml
Same as before but with duplicate names:
loader_LFD
loader_LFS
removed.
> Remove duplicate names

- sal_interfaces/DIMM/DIMM_Events.xml
- sal_interfaces/DIMM/DIMM_Telemetry.xml
- sal_interfaces/SALSubsystems.xml
This change is backward compatible because ts_dimm does not write any of those topics.
We should also remove the commands, but that has to be carefully scheduled, because it is not backwards compatible.
> DM-35663: remove most unused DIMM events and telemetry

- sal_interfaces/OCPS/OCPS_Commands.xml
prereq_jobs allows a comma-separated list of job ids to be provided; this job will not start until those jobs have completed. (DM-31689)
output_dataset_types allows a comma-separated list of glob patterns specifying dataset types to be provided.  Datasets matching those types will be captured by the UWS back-end system, and URIs pointing to those datasets will be included in the job result event. (DM-36672)
> DM-36189 (and DM-36672): Add prereq_jobs and output_dataset_types parameters.

- sal_interfaces/DIMM/DIMM_Telemetry.xml
- sal_interfaces/MTEEC/MTEEC_Events.xml
- sal_interfaces/MTM1M3/MTM1M3_Commands.xml
- schema/SALCommandSet.xsd
- schema/SALEventSet.xsd
- schema/SALTelemetrySet.xsd
- tests/test_CSC_XML_Valid.py
* Changed the <*ItemType> property from choice to sequence.
* Updated a few XML files with minimal changes needed to conform to the schema.
* Added skip tags for ATCamera, CCCamera and WeatherForecast CSCs.
> Tickets/dm 36708: Strictly enforce the <*ItemType> attribute ordering 

- python/lsst/ts/xml/data/sal_interfaces/MTMount/MTMount_Events.xml
The limits enabled fields did not match the information available from the TMA.
> DM-37113: MTMount_Events: fix cameraCableWrapControllerSettings

- python/lsst/ts/xml/data/sal_interfaces/ESS/ESS_Telemetry.xml
telemetry topics:
* accelerationPSD:
* change array length from 200 to 201. This gives nicer frequencies for round values of maxPSDFrequency.
* eliminate interval: it was irrelevant.
* eliminate  minPSDFrequency: it is now always 0.
* eliminate numDataPoints: it is now always 201 (all array elements).
* acceleration:
* change array length from 200 to 400. This allows publishing acceleration once for each time we publish acccelerationPSD.
> DM-38542: ESS: simplify acceleration and accelerationPSD

- python/lsst/ts/xml/data/sal_interfaces/ATWhiteLight/ATWhiteLight_Events.xml
fields and return LampControllerState_StandbyOrOn, instead of separate Standby and On values.
> DM-38724: ATWhiteLight: lampState: add lightDetected and ignitionFailures

- python/lsst/ts/xml/data/sal_interfaces/Script/Script_Events.xml
- python/lsst/ts/xml/data/sal_interfaces/ScriptQueue/ScriptQueue_Events.xml
Expand the description of the "instrument" field in the Script.metadata and ScriptQueue.nextVisit events.
> DM-37834: Script and ScriptQueue doc tweak

- doc/version-history.rst
- python/lsst/ts/xml/data/sal_interfaces/MTM2/MTM2_Events.xml
- python/lsst/ts/xml/field_info.py
Remove `unsigned long` and `unsigned long long` in MTM2.
> Use the string to replace the unsigned long and unsigned long long.

- doc/version-history.rst
- python/lsst/ts/xml/enums/LEDProjector.py
- python/lsst/ts/xml/field_info.py
- python/lsst/ts/xml/get_component_info.py
- tests/test_component_info.py
- tests/test_get_component_info.py
Changes involves:
- Fix type mapping SAL-long -> AVRO-int
- Add support for floating point values to be set as ``None``.
- Write a file with the list of revcodes.
- Copy the component xml files alongside the avro schema files and also generate the generics xml file.
> DM-41590: Fix type SAL-long type to AVRO-int

- doc/version-history.rst
- python/lsst/ts/xml/data/sal_interfaces/ATCamera/ATCamera_Events.xml
- python/lsst/ts/xml/data/sal_interfaces/ATCamera/ATCamera_Telemetry.xml
- python/lsst/ts/xml/data/sal_interfaces/CCCamera/CCCamera_Events.xml
- python/lsst/ts/xml/data/sal_interfaces/CCCamera/CCCamera_Telemetry.xml
- python/lsst/ts/xml/data/sal_interfaces/MTCamera/MTCamera_Events.xml
- python/lsst/ts/xml/data/sal_interfaces/MTCamera/MTCamera_Telemetry.xml
- tests/test_Units.py
* ATCamera/CCCamera/MTCamera
* Full refresh of camera Events/Telemetry XML based on currently installed CCS subsystems
* XML now based derived from https://github.com/lsst-camera-ccs/org-lsst-ccs-camera-sal-xml
* Current release: https://github.com/lsst-camera-ccs/org-lsst-ccs-camera-sal-xml/releases/tag/org-lsst-ccs-camera-sal-xml-parent-1.0.0
* Reviewing changes for individual CCS subsystem is possible by comparing to previous XML release., e.g. https://github.com/lsst-camera-ccs/org-lsst-ccs-camera-sal-xml/compare/refactor_XML_20...org-lsst-ccs-camera-sal-xml-parent-1.0.0#diff
> Update to new camera XML. New NONSTANDARD_UNITS added.

- doc/version-history.rst
- python/lsst/ts/xml/data/sal_interfaces/TunableLaser/TunableLaser_Commands.xml
- python/lsst/ts/xml/data/sal_interfaces/TunableLaser/TunableLaser_Events.xml
Adding three commands for the temperature control thermal sensor on the laser.
1. Changing the temperature set point
2. Turning it on
3. Turning it off
> Adding three commands to tunable laser for the thermal sensor

- doc/version-history.rst
- python/lsst/ts/xml/data/sal_interfaces/ATCamera/ATCamera_Events.xml
- python/lsst/ts/xml/data/sal_interfaces/CCCamera/CCCamera_Events.xml
- python/lsst/ts/xml/data/sal_interfaces/CCCamera/CCCamera_Telemetry.xml
- python/lsst/ts/xml/data/sal_interfaces/MTCamera/MTCamera_Events.xml
- python/lsst/ts/xml/data/sal_interfaces/MTCamera/MTCamera_Telemetry.xml
- tests/test_Units.py
Updated AT/CC/MT camera to the latest version (1.0.3) of org-lsst-ccs-camera-sal-xml
Release notes are here: https://jira.slac.stanford.edu/issues/?jql=project%20%3D%20LCOBM%20AND%20fixVersion%20%3D%20XML-1.0.3
Updated tests/test_Units.py to include one more non-standard unit used by camera.
Also fixed definition of rpm to include factor of 60 for minutes->seconds (someone should check this, I am really not sure if the 60 belongs in the numerator or the denominator, but I copied from gallon/min)
> ATCamera/CCCamera/MTCamera org-lsst-ccs-camera-sal-xml version 1.0.3

- doc/news/interface_changes/DM-42183.scheduler.rst
- doc/news/interface_changes/DM-42183.scriptqueue.rst
- python/lsst/ts/xml/data/sal_interfaces/SALSubsystems.xml
- python/lsst/ts/xml/enums/Scheduler.py
- python/lsst/ts/xml/enums/ScriptQueue.py
- towncrier.toml
Update Scheduler and ScriptQueue sal index enumerations to support a 3rd instance of each CSC.
> DM-42183: Update Scheduler to improve support for additional indices

- .github/workflows/ci.yaml
- doc/news/DM-43861.doc.rst
- doc/news/DM-43861.misc.rst
- pyproject.toml
The pipelines config that is available now imports from the guide
config. This means that the config expects to have any guide
dependency available but the documenteer pipeline group does not
have guide's group dependencies listed. So if we have only pipelines
listed, we don't get the guide's dependencies and thus missing
package errors start to appear. The solution is to add the
guide group to our install call which will catch any missing
packages in the future. Also simplified package install to one line
to save an unnecessary install step.
> Add guide to documenteer dependency grouping

- doc/news/interface_changes/DM-46165.tunablelaser.rst
- python/lsst/ts/xml/data/sal_interfaces/TunableLaser/TunableLaser_Commands.xml
- python/lsst/ts/xml/data/sal_interfaces/TunableLaser/TunableLaser_Events.xml
- python/lsst/ts/xml/enums/TunableLaser.py
Need to move the Optical Configuration enum from ts_TunableLaser to ts_xml so that we can change the optical configuration in scripts. This is necessary because we will swap between F1, F2 and direct for different tests.
> DM-46165: adding optical configuration to TunableLaser XML

- doc/news/interface_changes/DM-43793.atcamera.rst
- doc/news/interface_changes/DM-43804.cccamera.rst
- doc/news/interface_changes/DM-43816.mtcamera.rst
- python/lsst/ts/xml/data/sal_interfaces/ATCamera/ATCamera_Commands.xml
- python/lsst/ts/xml/data/sal_interfaces/ATCamera/ATCamera_Events.xml
- python/lsst/ts/xml/data/sal_interfaces/ATCamera/ATCamera_Telemetry.xml
- python/lsst/ts/xml/data/sal_interfaces/CCCamera/CCCamera_Commands.xml
- python/lsst/ts/xml/data/sal_interfaces/CCCamera/CCCamera_Events.xml
- python/lsst/ts/xml/data/sal_interfaces/CCCamera/CCCamera_Telemetry.xml
- python/lsst/ts/xml/data/sal_interfaces/MTCamera/MTCamera_Commands.xml
- python/lsst/ts/xml/data/sal_interfaces/MTCamera/MTCamera_Events.xml
- python/lsst/ts/xml/data/sal_interfaces/MTCamera/MTCamera_Telemetry.xml
- tests/test_TopicDescription.py
Descriptions have been added to all camera SAL topics.
The exceptions for the camera in  test_TopicDescription.py have been removed.
Many of these descriptions are auto-generated, so the content is what it is.
A few events have been marked with ??? indicating that I am not sure what they are for. I think these events are probably never issued and I will look into removing them (under a separate JIRA)
> Add descriptions to all atcamera/mtcamera/cccamera items

- doc/news/interface_changes/CAP-1064.cccamera.rst
- doc/news/interface_changes/CAP-1064.mtcamera.rst
- python/lsst/ts/xml/data/sal_interfaces/CCCamera/CCCamera_Events.xml
- python/lsst/ts/xml/data/sal_interfaces/MTCamera/MTCamera_Events.xml
- tests/test_Units.py
PR addressing changes required by the filter exchange system before Cycle 40 and described at
https://rubinobs.atlassian.net/browse/CAP-1064
including the addition of the new `g0` unit definition
https://rubinobs.atlassian.net/browse/CAP-1067
> Filter exchange system changes for Cycle 40

- doc/news/interface_changes/CAP-1064.mtcamera.rst
- python/lsst/ts/xml/data/sal_interfaces/MTCamera/MTCamera_Telemetry.xml
This is a direct consequence of fixing the fcs data dictionary to remove the registration of fake sensors that never published, which went unseen up to now.
This file was created with 
org-lsst-ccs-camera-sal-xml for the cycle40 SAL release.
> Update Filter exchange system telemetry

- doc/news/interface_changes/CAP-1062.atcamera.rst
- doc/news/interface_changes/CAP-1062.cccamera.rst
- doc/news/interface_changes/CAP-1062.mtcamera.rst
- python/lsst/ts/xml/data/sal_interfaces/ATCamera/ATCamera_Commands.xml
- python/lsst/ts/xml/data/sal_interfaces/CCCamera/CCCamera_Commands.xml
- python/lsst/ts/xml/data/sal_interfaces/MTCamera/MTCamera_Commands.xml
This implements a generic command to allow us to issue "arbitrary" commands to the camera
Commands will only be accepted if the camera configuration allows it.
This is intended to give us a way to allow commands if an urgent need is discovered during commisioning/operations without waiting for an XML release.
> Implement CAP-1062 (Generic command)

- doc/news/interface_changes/DM-51223.dream.rst
- python/lsst/ts/xml/data/sal_interfaces/SALSubsystems.xml
Backs out PR #959 and makes DREAM an indexed CSC, consistent with past deployments.
> DM-51223 Update DREAM interface so that it is indexed.

- doc/news/interface_changes/OSW-29.dimm.1.rst
- doc/news/interface_changes/OSW-29.dimm.2.rst
- doc/news/interface_changes/OSW-29.dimm.rst
- python/lsst/ts/xml/data/sal_interfaces/DIMM/DIMM_Commands.xml
- python/lsst/ts/xml/data/sal_interfaces/DIMM/DIMM_Events.xml
New commands:
- `controllerCommand`
- `recover`
- `park`
Updated commands:
- `gotoRaDec` and `gotoAltAz` now have optional items `mag`, `bv`, `stype`.
- `moveDome` now has item `open`.
New events:
- `automationState`, the current AMEBA state
- `scopeEvents` a list of error events from the scope
> OSW-29: Updated commands for DIMM

- doc/news/interface_changes/CAP-1084.atcamera.rst
- doc/news/interface_changes/CAP-1084.cccamera.rst
- doc/news/interface_changes/CAP-1084.mtcamera.rst
- python/lsst/ts/xml/data/sal_interfaces/ATCamera/ATCamera_Events.xml
- python/lsst/ts/xml/data/sal_interfaces/CCCamera/CCCamera_Events.xml
- python/lsst/ts/xml/data/sal_interfaces/MTCamera/MTCamera_Events.xml
- python/lsst/ts/xml/data/sal_interfaces/MTCamera/MTCamera_Telemetry.xml
Changes for auxtel and lsstcam.
Note that we have not regenerated dictionaries for comcam, and cannot since it has not been kept up to date. It will almost certainly be necessary to make a new XML release before comcam can be bought back under OCS control, but that is probably a ways off still.
> Implement CAP-1084
